"""
Central repository for constants used throughout the surgery scheduling application.
This includes DataFrame column names, feature set definitions, fixed domain values,
Gurobi-related identifiers, logging settings, and JSON output keys.
"""

# --- DataFrame Column Names (Standardized Snake Case) ---
# Raw Excel columns are mapped to these during initial data loading.

# Primary Identifiers & Categorical
COL_PATIENT_ID: str = "patient_id"
COL_PATIENT_TYPE: str = "patient_type"
COL_CASE_SERVICE: str = "case_service"
COL_MAIN_PROCEDURE: str = "main_procedure"
COL_MAIN_PROCEDURE_ID: str = "main_procedure_id"
COL_OPERATING_ROOM: str = "operating_room"
COL_SURGEON: str = "surgeon"
COL_SURGEON_CODE: str = "surgeon_code"
COL_CMG: str = "cmg" # Case Mix Group
COL_CMG_DESCRIPTION: str = "cmg_description"
COL_ANAESTHETIC_TYPE_GIVEN: str = "anaesthetic_type_given"
COL_START_DELAY_REASON: str = "start_delay_reason"
COL_PATIENT_DISPOSITION_FROM_OR: str = "patient_disposition_from_or"
COL_CASE_CANCELLED_REASON: str = "case_cancelled_reason"

# Dates & Times (Original Parts)
COL_CONSULT_DATE: str = "consult_date"
COL_DECISION_DATE: str = "decision_date"
COL_ENTER_ROOM_DATE: str = "enter_room_date"
COL_ENTER_ROOM_TIME: str = "enter_room_time"
COL_ACTUAL_START_DATE: str = "actual_start_date"
COL_ACTUAL_START_TIME: str = "actual_start_time"
COL_ACTUAL_STOP_DATE: str = "actual_stop_date"
COL_ACTUAL_STOP_TIME: str = "actual_stop_time"
COL_LEAVE_ROOM_DATE: str = "leave_room_date"
COL_LEAVE_ROOM_TIME: str = "leave_room_time"
COL_ADMIT_RECOVERY_DATE: str = "admit_recovery_date"
COL_ADMIT_RECOVERY_TIME: str = "admit_recovery_time"
COL_LEAVE_RECOVERY_DATE: str = "leave_recovery_date"
COL_LEAVE_RECOVERY_TIME: str = "leave_recovery_time"
COL_CASE_CANCEL_DATE: str = "case_cancel_date"
COL_CASE_CANCEL_TIME: str = "case_cancel_time"

# Durations
COL_RECOVERY_TIME_MINS: str = "recovery_time_mins"

# Derived Datetime Columns (after combining date and time parts)
COL_ENTER_ROOM: str = "enter_room"
COL_ACTUAL_START: str = "actual_start"       # Primary timestamp for events
COL_ACTUAL_STOP: str = "actual_stop"
COL_LEAVE_ROOM: str = "leave_room"
COL_ADMIT_RECOVERY: str = "admit_recovery"
COL_LEAVE_RECOVERY: str = "leave_recovery"

# Derived Duration Columns (calculated in minutes)
COL_PREPARATION_DURATION_MIN: str = "preparation_duration_min"
COL_PROCEDURE_DURATION_MIN: str = "procedure_duration_min" # Target variable for prediction

# Aliases & Convenience Columns
COL_BOOKED_MIN: str = "booked_time_minutes" 

# Time Features (derived from COL_ACTUAL_START for modeling)
COL_WEEK_OF_YEAR: str = "week_of_year"
COL_MONTH: str = "month"
COL_YEAR: str = "year"

# --- Schedule DataFrame Column Names (Output from Solvers) ---
# These are typically used in DataFrames generated by `extract_schedule`
COL_SURGERY_ID: str = "SurgeryID"         # Original surgery identifier (often DataFrame index)
COL_PROC_ID: str = "ProcID"            # Procedure ID (e.g., COL_MAIN_PROCEDURE_ID value)
COL_ASSIGNED_DAY: str = "AssignedDay"   # Day index (0 to H-1) or "Rejected"
COL_ASSIGNED_BLOCK: str = "AssignedBlock" # Block index (0 to B-1) or pd.NA
COL_ACTUAL_DUR_MIN: str = "ActualDurMin" # Actual duration used for evaluation

# --- Feature Sets for Machine Learning Models ---
NUMERIC_FEATURE_COLS: list[str] = [
    COL_BOOKED_MIN, 
    COL_WEEK_OF_YEAR,
    COL_MONTH,
    COL_YEAR,
]

CATEGORICAL_FEATURE_COLS: list[str] = [
    COL_PATIENT_TYPE,
    COL_MAIN_PROCEDURE_ID,
    COL_SURGEON_CODE,
    COL_CASE_SERVICE,
]

ALL_FEATURE_COLS: list[str] = NUMERIC_FEATURE_COLS + CATEGORICAL_FEATURE_COLS

# Specific numeric keys for the 'theta_predictor' (raw, before potential scaling)
THETA_NUMERIC_KEYS_RAW: list[str] = [
    COL_BOOKED_MIN, COL_WEEK_OF_YEAR, COL_MONTH, COL_YEAR
]


# --- Domain-Specific Numerical Constants ---
MIN_PROCEDURE_DURATION: float = 1.0   # Minimum allowed duration for a procedure (minutes)
MAX_OVERTIME_MINUTES_PER_BLOCK: int = 120 # Max allowable overtime for a block in solver (minutes)
DEFAULT_BLOCK_SIZE_MINUTES: int = 480 # Default OR block size, e.g., 8 hours (minutes)

SECONDS_PER_MINUTE: int = 60
DEFAULT_TIME_STR: str = "00:00:00"   # Default time string for parsing if time part is missing


# --- Categorical Value Constants ---
OTHER_CATEGORY: str = "Other"        # For recoding rare categories
UNKNOWN_CATEGORY: str = "Unknown"      # For missing categorical values during prediction
EMERGENCY_PATIENT_CATEGORY: str = "EMERGENCY PATIENT" # Patient type to exclude
OR_ROOM_PREFIX: str = "OR"           # Prefix for valid operating room names


# --- Gurobi Related Constants ---
# Prefixes for Gurobi variable names (used for consistent naming in models)
GUROBI_VAR_X_PREFIX: str = "x"          # Assignment variables x[i,d,b]
GUROBI_VAR_R_PREFIX: str = "r"          # Rejection variables r[i]
GUROBI_VAR_OT_PREFIX: str = "ot"        # Overtime variables ot[d,b]
GUROBI_VAR_IT_PREFIX: str = "it"        # Idle time variables it[d,b]
GUROBI_VAR_ZSPILL_PREFIX: str = "zspill"    # Spillover binary variables z[i,d,b]
GUROBI_VAR_THETA_PREFIX: str = "theta"     # Theta coefficients theta[j] (integrated/Benders)
GUROBI_VAR_ETA_PREFIX: str = "eta"        # Eta variables (Benders master problem recourse) eta[w]
GUROBI_VAR_ABS_THETA_PREFIX: str = "abs_theta" # Absolute value of theta (for L1 penalty)
GUROBI_VAR_BLK_SIGNED_ERR_PREFIX: str = "blk_signed_err" # Block signed error (integrated model)
GUROBI_VAR_BLK_ABS_ERR_PREFIX: str = "blk_abs_err"   # Block absolute error (integrated model)
GUROBI_VAR_U_LEARN_ABS_ERROR_PREFIX = "u_abs_learn_err"

# Fixed Gurobi parameter values (see Gurobi documentation for meanings)
# These are typically set via GRB.Param.NamedConstant.
# Configurable values (like TimeLimit, MIPGap) are in PARAMS.
GUROBI_OUTPUT_FLAG_SILENT: int = 0
GUROBI_OUTPUT_FLAG_VERBOSE: int = 1
GUROBI_THREADS_ALL_CORES: int = 0      # Gurobi automatically determines thread count
GUROBI_PRESOLVE_AUTO: int = -1         # Gurobi determines presolve level
GUROBI_MIP_FOCUS_BALANCED: int = 0     # Default MIP focus
GUROBI_MIP_FOCUS_FEASIBILITY: int = 1  # Focus on finding feasible solutions quickly
GUROBI_MIP_FOCUS_OPTIMALITY: int = 2   # Focus on proving optimality
GUROBI_MIP_FOCUS_BOUND: int = 3        # Focus on improving the MIP bound
GUROBI_LAZY_CONSTRAINTS_ENABLED: int = 1 # For enabling lazy constraints (Benders)

# Other Gurobi related values
DEFAULT_GUROBI_MODEL_NAME: str = "GurobiModel" # Fallback name if model.ModelName is not set
REGEX_NUMERICAL_VALUES: str = r"\d+"    # Regex for extracting numbers from Gurobi var names
GUROBI_BINARY_THRESHOLD: float = 0.5   # Value below which a binary var is considered "off" (e.g. var.X < 0.5)


# --- SAA (Sample Average Approximation) ---
DEFAULT_SAA_RANDOM_SEED: int = 42


# --- Logging Configuration ---
DEFAULT_LOGGER_NAME: str = "SurgerySchedulingApp"
LOG_FORMAT: str = "%(asctime)s - %(name)s - %(levelname)s - %(module)s.%(funcName)s - %(message)s"
LOG_DATE_FORMAT: str = "%Y-%m-%d %H:%M:%S"


# --- Internal Cache Keys / Parameter Dictionary Keys ---
# Key for caching mu/sigma in DataFrame.attrs for build_feature_vector
BFV_MU_SIGMA_CACHE_KEY: str = "bfv_mu_sigma_scaling_cache"
# Key for passing horizon start date in params dict to compute_block_capacity
HORIZON_START_DATE_PARAM_KEY: str = "_internal_horizon_start_date"


# --- Machine Learning Model Feature Scaling Options ---
SCALING_STD: str = "std" # Standard scaling (z-score)
SCALING_RAW: str = "raw" # No scaling, use raw feature values


# --- JSON Output File Keys (for structuring results.json, agg_results.json) ---
# Main Structure
JSON_KEY_CONFIG: str = "config"
JSON_KEY_HORIZONS: str = "horizons"
JSON_KEY_AGGREGATE: str = "aggregate"

# Config Sub-keys
JSON_KEY_CONFIG_SAA_SCENARIOS: str = "saa_scenarios_configured"
JSON_KEY_CONFIG_NUM_HORIZONS: str = "num_horizons_planned"

# Per-Horizon Entry
JSON_KEY_HORIZON_INDEX: str = "horizon_index"
JSON_KEY_START_DATE: str = "start_date"
JSON_KEY_STATUS: str = "solver_status"
JSON_KEY_PLANNED_COST: str = "planned_objective_cost"
JSON_KEY_ACTUAL_COST: str = "actual_total_cost"
JSON_KEY_OVERTIME_MIN: str = "overtime_minutes_total"
JSON_KEY_IDLE_MIN: str = "idle_minutes_total"
JSON_KEY_SCHEDULED_COUNT: str = "scheduled_surgeries_count"
JSON_KEY_REJECTED_COUNT: str = "rejected_surgeries_count"
JSON_KEY_RUNTIME_SEC: str = "solver_runtime_seconds"

# Aggregate Results Keys (per method)
JSON_KEY_MEDIAN_PLANNED_COST: str = "median_planned_objective_cost"
JSON_KEY_AVG_PLANNED_COST: str = "average_planned_objective_cost"
JSON_KEY_MEDIAN_ACTUAL_COST: str = "median_actual_total_cost"
JSON_KEY_AVG_ACTUAL_COST: str = "average_actual_total_cost"
JSON_KEY_MEDIAN_OVERTIME_MIN: str = "median_overtime_minutes"
JSON_KEY_AVG_OVERTIME_MIN: str = "average_overtime_minutes"
JSON_KEY_MEDIAN_IDLE_MIN: str = "median_idle_minutes"
JSON_KEY_AVG_IDLE_MIN: str = "average_idle_minutes"
JSON_KEY_AVG_RUNTIME_SEC: str = "average_runtime_seconds"
JSON_KEY_MEDIAN_SCHEDULED: str = "median_scheduled_surgeries"
JSON_KEY_AVG_SCHEDULED: str = "average_scheduled_surgeries"
JSON_KEY_MEDIAN_REJECTED: str  = "median_rejected_surgeries"
JSON_KEY_AVG_REJECTED: str  = "average_rejected_surgeries"